# -*- coding: utf-8 -*-
"""embedding_index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATkE5ijrYLYuUk7iCCtvqoo6I6T80IKP
"""

# Initialize the embedding model
embedding_model = SentenceTransformer('distiluse-base-multilingual-cased-v1')

# Initialize FAISS index
embedding_dim = embedding_model.get_sentence_embedding_dimension()
index = faiss.IndexFlatL2(embedding_dim)

def add_documents_to_index(documents):
    embeddings = embedding_model.encode(documents)
    print("Embedding shape:", embeddings.shape)  # Check embedding size
    index.add(np.array(embeddings))
    print("Index size after adding:", index.ntotal)  # Check total embeddings in index