# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r7ty-tzN1k5QPI3_9BfkvJzlqI5DVuoH
"""

# Example usage

# List of PDF paths
pdf_paths = ['your_pdf_path.pdf']  # Update with your PDF paths

# Initialize an empty string to hold all extracted text
all_extracted_text = ""

# Extract text from all PDFs
for pdf_path in pdf_paths:
    if pdf_path.endswith('.pdf'):
        extracted_text = extract_text(pdf_path)
        all_extracted_text += extracted_text

# Clean the extracted text
cleaned_text = clean_text(all_extracted_text)
print("Extracted and cleaned text length:", len(cleaned_text))

# Detect language
language = detect_language(cleaned_text)
print(f"Detected language: {language}")

# Chunk the cleaned text
chunks = chunk_text(cleaned_text)
print("Number of chunks:", len(chunks))

# Add chunks to FAISS index
add_documents_to_index(chunks)

# Initialize BM25 for keyword-based search
bm25 = initialize_bm25(chunks)

# User query
query = "What is the main topic of the document?"
response = answer_query_with_memory(query, chunks, bm25)
print("Answer:", response)