# -*- coding: utf-8 -*-
"""qa_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XR0rCNuRwf6-9ZUZBqXXDubaGDAo1y8
"""

# Initialize the QA model
qa_model = pipeline('question-answering', model='deepset/xlm-roberta-large-squad2')