# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDKK4fzMATvqQyB6oOCEvBzQquntXyCf
"""

# Install necessary dependencies
!apt-get install -y poppler-utils tesseract-ocr libtesseract-dev
!pip install pytesseract pdf2image PyMuPDF
!pip install transformers
!pip install sentence-transformers
!pip install faiss-cpu
!pip install rank-bm25
!pip install langdetect

import pytesseract
from pdf2image import convert_from_path
import fitz  # PyMuPDF
import re
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss
from transformers import pipeline
from rank_bm25 import BM25Okapi
import os
from langdetect import detect