# -*- coding: utf-8 -*-
"""text_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-J8TQc-9C1zQTiypfwZ2enUzxSNx7YPo
"""

def extract_text(pdf_path):
    text = ""
    try:
        # Try extracting text using PyMuPDF (for digital PDFs)
        with fitz.open(pdf_path) as pdf_document:
            for page_num in range(len(pdf_document)):
                page = pdf_document.load_page(page_num)
                text += page.get_text("text")
        if text.strip():
            return text
    except Exception as e:
        print(f"Error extracting text with PyMuPDF: {e}")

    # If text extraction failed, try OCR (for scanned PDFs)
    try:
        print("Attempting OCR extraction...")
        images = convert_from_path(pdf_path)
        extracted_text = ""
        for image in images:
            text = pytesseract.image_to_string(image, lang='eng+hin+ben+chi_sim')
            extracted_text += text
        return extracted_text
    except Exception as e:
        print(f"Error extracting text with OCR: {e}")
        return ""