# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-H-Xf68OOJFrxeaiHQKq8p0cLgc9PIa
"""

def clean_text(text):
    # Remove unwanted characters and extra spaces
    clean_text = text.replace('\n', ' ').replace('\x07', '').replace('\x03', '')
    clean_text = re.sub(r'\s+', ' ', clean_text)
    return clean_text.strip()

def detect_language(text): #detecting launguage
    try:
        language = detect(text)
        return language
    except Exception as e:
        print(f"Language detection failed: {e}")
        return 'en'  # Default to English if detection fails